name: schedular_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  flutter_slidable: ^2.0.0
  firebase_messaging: ^12.0.1
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  flutter_local_notifications: ^9.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/.env